Index: openmx-3.5/source/makefile
===================================================================
--- openmx-3.5.orig/source/makefile	2011-08-03 09:19:11.000000000 +0200
+++ openmx-3.5/source/makefile	2011-08-03 09:19:43.000000000 +0200
@@ -95,8 +95,8 @@
 #
 
 
-CC      = gcc -O3 -Dnompi -Dnoomp -I/usr/local/include -I/home/ozaki/include
-LIB     = -L/usr/local/lib -lfftw3 -llapack -lblas -lg2c -static
+CC      = gcc -O3 -Dnompi -Dnoomp
+LIB     = -lfftw3 -llapack -lblas
 
 
 
@@ -554,7 +554,7 @@
 
 install:	$(PROG)
 	strip $(PROG)
-	cp $(PROG) $(DESTDIR)/$(PROG)
+	cp $(PROG) $(DESTDIR)/usr/bin/$(PROG)
 
 #
 #
