.TH "OPENMX" "1" "2007-06-09" "" ""
.SH NAME
openmx \- package for nano-scale material simulations

.SH SYNOPSIS
.B openmx
.BI [ file ]

.SH DESCRIPTION
.B openmx
is a program that calculates electronic structure using DFT.

.SH OPTIONS
The program doesn't accept any other options, everything is given in the file
specified at the command line.

.SH AUTHORS
This manual page was written by \fBOndrej Certik\fR <\&ondrej@certik.cz\&> for
the Debian system (but may be used by others).
.PP
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU General Public License, Version 2 or (at your option) any
later version as published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be
found in \fI\%/usr/share/common-licenses/GPL\fR.
